/*
 * - Ref: https://cran.r-project.org/web/packages/countrycode/countrycode.pdf
 *
 * - ccTLD: IANA country code top-level domain
 * - country.name: country name (English)
 * - country.name.de: country name (German)
 * - cowc: Correlates of War character
 * - cown: Correlates of War numeric
 * - dhs: Demographic and Health Surveys Program
 * - ecb: European Central Bank
 * - eurostat: Eurostat
 * - fao: Food and Agriculture Organization of the United Nations numerical code
 * - fips: FIPS 10-4 (Federal Information Processing Standard)
 * - gaul: Global Administrative Unit Layers
 * - genc2c: GENC 2-letter code
 * - genc3c: GENC 3-letter code
 * - genc3n: GENC numeric code
 * - gwc: Gleditsch & Ward character
 * - gwn: Gleditsch & Ward numeric
 * - imf: International Monetary Fund
 * - ioc: International Olympic Committee
 * - iso2c: ISO-2 character
 * - iso3c: ISO-3 character
 * - iso3n: ISO-3 numeric
 * - p4n: Polity IV numeric country code
 * - p4c: Polity IV character country code
 * - un: United Nations M49 numeric codes
 * - unicode.symbol: Region subtag (often displayed as emoji flag)
 * - unpd: United Nations Procurement Division
 * - vdem: Varieties of Democracy (V-Dem version 8, April 2018)
 * - wb: World Bank (very similar but not identical to iso3c)
 * - wvs: World Values Survey numeric code
 * - ar5: IPCC’s regional mapping used both in the Fifth Assessment Report (AR5) and for the
 * - Reference Concentration Pathways (RCP)
 * - continent: Continent as defined in the World Bank Development Indicators
 * - cow.name: Correlates of War country name
 * - currency: ISO 4217 currency name
 * - eurocontrol_pru: European Organisation for the Safety of Air Navigation
 * - eurocontrol_statfor: European Organisation for the Safety of Air Navigation
 * - eu28: Member states of the European Union (as of December 2015), without special territories
 * - icao.region: International Civil Aviation Organization region
 * - iso.name.en: ISO English short name
 * - iso.name.fr: ISO French short name
 * - iso4217c: ISO 4217 currency alphabetic code
 * - iso4217n: ISO 4217 currency numeric code
 * - p4.name: Polity IV country name
 * - region: 7 Regions as defined in the World Bank Development Indicators
 * - region23: 23 Regions as used to be in the World Bank Development Indicators (legacy)
 * - un.name.ar: United Nations Arabic country name
 * - un.name.en: United Nations English country name
 * - un.name.es: United Nations Spanish country name
 * - un.name.fr: United Nations French country name
 * - un.name.ru: United Nations Russian country name
 * - un.name.zh: United Nations Chinese country name
 * - un.region.name: United Nations region name
 * - un.region.code: United Nations region code
 * - un.regionintermediate.name: United Nations intermediate region name
 * - un.regionintermediate.code: United Nations intermediate region code
 * - un.regionsub.name: United Nations sub-region name
 * - un.regionsub.code: United Nations sub-region code
 * - wvs.name: World Values Survey numeric code country name
 * - cldr.*: 600+ country name variants from the UNICODE CLDR project
 */
export type Country = {
  ar5: string | null
  cctld: string | null
  continent: string | null
  'country.name.de': string | null
  'country.name.de.regex': string | null
  'country.name.en': string | null
  'country.name.en.regex': string | null
  'cow.name': string | null
  cowc: string | null
  cown: number | null
  currency: string | null
  dhs: string | null
  ecb: string | null
  eu28: string | null
  eurocontrol_pru: string | null
  eurocontrol_statfor: string | null
  eurostat: string | null
  fao: number | null
  fips: string | null
  gaul: number | null
  genc2c: string | null
  genc3c: string | null
  genc3n: string | null
  gwc: string | null
  gwn: number | null
  'icao.region': string | null
  imf: number | null
  ioc: string | null
  'iso.name.en': string | null
  'iso.name.fr': string | null
  iso2c: string | null
  iso3c: string | null
  iso3n: number | null
  iso4217c: string | null
  iso4217n: number | null
  'p4.name': string | null
  p4c: string | null
  p4n: number | null
  region: string | null
  region23: string | null
  un: number | null
  'un.name.ar': string | null
  'un.name.en': string | null
  'un.name.es': string | null
  'un.name.fr': string | null
  'un.name.ru': string | null
  'un.name.zh': string | null
  'un.region.code': number | null
  'un.region.name': string | null
  'un.regionintermediate.code': null | null
  'un.regionintermediate.name': string | null
  'un.regionsub.code': number | null
  'un.regionsub.name': string | null
  'unicode.symbol': string | null
  unpd: number | null
  vdem: number | null
  'vdem.name': string | null
  wb: string | null
  wb_api2c: string | null
  wb_api3c: string | null
  wvs: number | null
  'cldr.name.af': string | null
  'cldr.name.agq': string | null
  'cldr.name.ak': string | null
  'cldr.name.am': string | null
  'cldr.name.ar': string | null
  'cldr.name.ar_ly': string | null
  'cldr.name.ar_sa': string | null
  'cldr.name.as': string | null
  'cldr.name.asa': string | null
  'cldr.name.ast': string | null
  'cldr.name.az': string | null
  'cldr.name.az_cyrl': string | null
  'cldr.name.bas': string | null
  'cldr.name.be': string | null
  'cldr.name.bem': string | null
  'cldr.name.bez': string | null
  'cldr.name.bg': string | null
  'cldr.name.bm': string | null
  'cldr.name.bn': string | null
  'cldr.name.bo': string | null
  'cldr.name.br': string | null
  'cldr.name.brx': string | null
  'cldr.name.bs': string | null
  'cldr.name.bs_cyrl': string | null
  'cldr.name.ca': string | null
  'cldr.name.ccp': string | null
  'cldr.name.ce': string | null
  'cldr.name.ceb': string | null
  'cldr.name.cgg': string | null
  'cldr.name.chr': string | null
  'cldr.name.ckb': string | null
  'cldr.name.cs': string | null
  'cldr.name.cu': string | null
  'cldr.name.cy': string | null
  'cldr.name.da': string | null
  'cldr.name.dav': string | null
  'cldr.name.de': string | null
  'cldr.name.de_at': string | null
  'cldr.name.de_ch': string | null
  'cldr.name.dje': string | null
  'cldr.name.dsb': string | null
  'cldr.name.dua': string | null
  'cldr.name.dyo': string | null
  'cldr.name.dz': string | null
  'cldr.name.ee': string | null
  'cldr.name.el': string | null
  'cldr.name.en': string | null
  'cldr.name.en_001': string | null
  'cldr.name.en_au': string | null
  'cldr.name.eo': string | null
  'cldr.name.es': string | null
  'cldr.name.es_419': string | null
  'cldr.name.es_ar': string | null
  'cldr.name.es_cl': string | null
  'cldr.name.es_mx': string | null
  'cldr.name.es_us': string | null
  'cldr.name.et': string | null
  'cldr.name.eu': string | null
  'cldr.name.ewo': string | null
  'cldr.name.fa': string | null
  'cldr.name.fa_af': string | null
  'cldr.name.ff': string | null
  'cldr.name.fi': string | null
  'cldr.name.fil': string | null
  'cldr.name.fo': string | null
  'cldr.name.fr': string | null
  'cldr.name.fr_be': string | null
  'cldr.name.fr_ca': string | null
  'cldr.name.fur': string | null
  'cldr.name.fy': string | null
  'cldr.name.ga': string | null
  'cldr.name.gd': string | null
  'cldr.name.gl': string | null
  'cldr.name.gsw': string | null
  'cldr.name.gu': string | null
  'cldr.name.gv': string | null
  'cldr.name.ha': string | null
  'cldr.name.haw': string | null
  'cldr.name.he': string | null
  'cldr.name.hi': string | null
  'cldr.name.hr': string | null
  'cldr.name.hsb': string | null
  'cldr.name.hu': string | null
  'cldr.name.hy': string | null
  'cldr.name.ia': string | null
  'cldr.name.id': string | null
  'cldr.name.ig': string | null
  'cldr.name.ii': string | null
  'cldr.name.is': string | null
  'cldr.name.it': string | null
  'cldr.name.ja': string | null
  'cldr.name.jgo': string | null
  'cldr.name.jv': string | null
  'cldr.name.ka': string | null
  'cldr.name.kab': string | null
  'cldr.name.kam': string | null
  'cldr.name.kde': string | null
  'cldr.name.kea': string | null
  'cldr.name.khq': string | null
  'cldr.name.ki': string | null
  'cldr.name.kk': string | null
  'cldr.name.kkj': string | null
  'cldr.name.kl': string | null
  'cldr.name.kln': string | null
  'cldr.name.km': string | null
  'cldr.name.kn': string | null
  'cldr.name.ko': string | null
  'cldr.name.ko_kp': string | null
  'cldr.name.kok': string | null
  'cldr.name.ks': string | null
  'cldr.name.ksb': string | null
  'cldr.name.ksf': string | null
  'cldr.name.ksh': string | null
  'cldr.name.ku': string | null
  'cldr.name.kw': string | null
  'cldr.name.ky': string | null
  'cldr.name.lag': string | null
  'cldr.name.lb': string | null
  'cldr.name.lg': string | null
  'cldr.name.lkt': string | null
  'cldr.name.ln': string | null
  'cldr.name.lo': string | null
  'cldr.name.lrc': string | null
  'cldr.name.lt': string | null
  'cldr.name.lu': string | null
  'cldr.name.luo': string | null
  'cldr.name.luy': string | null
  'cldr.name.lv': string | null
  'cldr.name.mas': string | null
  'cldr.name.mer': string | null
  'cldr.name.mfe': string | null
  'cldr.name.mg': string | null
  'cldr.name.mgh': string | null
  'cldr.name.mgo': string | null
  'cldr.name.mi': string | null
  'cldr.name.mk': string | null
  'cldr.name.ml': string | null
  'cldr.name.mn': string | null
  'cldr.name.mr': string | null
  'cldr.name.ms': string | null
  'cldr.name.mt': string | null
  'cldr.name.mua': string | null
  'cldr.name.my': string | null
  'cldr.name.mzn': string | null
  'cldr.name.naq': string | null
  'cldr.name.nb': string | null
  'cldr.name.nd': string | null
  'cldr.name.ne': string | null
  'cldr.name.nl': string | null
  'cldr.name.nmg': string | null
  'cldr.name.nn': string | null
  'cldr.name.nnh': string | null
  'cldr.name.nus': string | null
  'cldr.name.nyn': string | null
  'cldr.name.om': string | null
  'cldr.name.or': string | null
  'cldr.name.os': string | null
  'cldr.name.pa': string | null
  'cldr.name.pa_arab': string | null
  'cldr.name.pl': string | null
  'cldr.name.ps': string | null
  'cldr.name.ps_pk': string | null
  'cldr.name.pt': string | null
  'cldr.name.pt_ao': string | null
  'cldr.name.qu': string | null
  'cldr.name.rm': string | null
  'cldr.name.rn': string | null
  'cldr.name.ro': string | null
  'cldr.name.ro_md': string | null
  'cldr.name.rof': string | null
  'cldr.name.ru': string | null
  'cldr.name.ru_ua': string | null
  'cldr.name.rw': string | null
  'cldr.name.sah': string | null
  'cldr.name.sbp': string | null
  'cldr.name.sd': string | null
  'cldr.name.se': string | null
  'cldr.name.se_fi': string | null
  'cldr.name.seh': string | null
  'cldr.name.sg': string | null
  'cldr.name.shi': string | null
  'cldr.name.shi_latn': string | null
  'cldr.name.si': string | null
  'cldr.name.sk': string | null
  'cldr.name.sl': string | null
  'cldr.name.smn': string | null
  'cldr.name.sn': string | null
  'cldr.name.so': string | null
  'cldr.name.sq': string | null
  'cldr.name.sr': string | null
  'cldr.name.sr_cyrl_ba': string | null
  'cldr.name.sr_cyrl_me': string | null
  'cldr.name.sr_cyrl_xk': string | null
  'cldr.name.sr_latn': string | null
  'cldr.name.sr_latn_ba': string | null
  'cldr.name.sr_latn_me': string | null
  'cldr.name.sr_latn_xk': string | null
  'cldr.name.sv': string | null
  'cldr.name.sw': string | null
  'cldr.name.sw_cd': string | null
  'cldr.name.sw_ke': string | null
  'cldr.name.ta': string | null
  'cldr.name.te': string | null
  'cldr.name.teo': string | null
  'cldr.name.tg': string | null
  'cldr.name.th': string | null
  'cldr.name.ti': string | null
  'cldr.name.tk': string | null
  'cldr.name.to': string | null
  'cldr.name.tr': string | null
  'cldr.name.tt': string | null
  'cldr.name.twq': string | null
  'cldr.name.tzm': string | null
  'cldr.name.ug': string | null
  'cldr.name.uk': string | null
  'cldr.name.ur': string | null
  'cldr.name.ur_in': string | null
  'cldr.name.uz': string | null
  'cldr.name.uz_arab': string | null
  'cldr.name.uz_cyrl': string | null
  'cldr.name.vai': string | null
  'cldr.name.vai_latn': string | null
  'cldr.name.vi': string | null
  'cldr.name.wae': string | null
  'cldr.name.wo': string | null
  'cldr.name.xh': string | null
  'cldr.name.xog': string | null
  'cldr.name.yav': string | null
  'cldr.name.yi': string | null
  'cldr.name.yo': string | null
  'cldr.name.yo_bj': string | null
  'cldr.name.yue': string | null
  'cldr.name.yue_hans': string | null
  'cldr.name.zgh': string | null
  'cldr.name.zh': string | null
  'cldr.name.zh_hant': string | null
  'cldr.name.zh_hant_hk': string | null
  'cldr.name.zu': string | null
  'cldr.short.af': string | null
  'cldr.short.agq': string | null
  'cldr.short.ak': string | null
  'cldr.short.am': string | null
  'cldr.short.ar': string | null
  'cldr.short.ar_ly': string | null
  'cldr.short.ar_sa': string | null
  'cldr.short.as': string | null
  'cldr.short.asa': string | null
  'cldr.short.ast': string | null
  'cldr.short.az': string | null
  'cldr.short.az_cyrl': string | null
  'cldr.short.bas': string | null
  'cldr.short.be': string | null
  'cldr.short.bez': string | null
  'cldr.short.bg': string | null
  'cldr.short.bm': string | null
  'cldr.short.bn': string | null
  'cldr.short.bo': string | null
  'cldr.short.br': string | null
  'cldr.short.brx': string | null
  'cldr.short.bs': string | null
  'cldr.short.bs_cyrl': string | null
  'cldr.short.ca': string | null
  'cldr.short.ccp': string | null
  'cldr.short.ce': string | null
  'cldr.short.ceb': string | null
  'cldr.short.cgg': string | null
  'cldr.short.chr': string | null
  'cldr.short.ckb': string | null
  'cldr.short.cs': string | null
  'cldr.short.cy': string | null
  'cldr.short.da': string | null
  'cldr.short.dav': string | null
  'cldr.short.de': string | null
  'cldr.short.de_at': string | null
  'cldr.short.de_ch': string | null
  'cldr.short.dje': string | null
  'cldr.short.dsb': string | null
  'cldr.short.dz': string | null
  'cldr.short.ee': string | null
  'cldr.short.el': string | null
  'cldr.short.en': string | null
  'cldr.short.en_001': string | null
  'cldr.short.en_au': string | null
  'cldr.short.eo': string | null
  'cldr.short.es': string | null
  'cldr.short.es_419': string | null
  'cldr.short.es_ar': string | null
  'cldr.short.es_cl': string | null
  'cldr.short.es_mx': string | null
  'cldr.short.es_us': string | null
  'cldr.short.et': string | null
  'cldr.short.eu': string | null
  'cldr.short.ewo': string | null
  'cldr.short.fa': string | null
  'cldr.short.fa_af': string | null
  'cldr.short.ff': string | null
  'cldr.short.fi': string | null
  'cldr.short.fil': string | null
  'cldr.short.fo': string | null
  'cldr.short.fr': string | null
  'cldr.short.fr_be': string | null
  'cldr.short.fr_ca': string | null
  'cldr.short.fur': string | null
  'cldr.short.fy': string | null
  'cldr.short.ga': string | null
  'cldr.short.gd': string | null
  'cldr.short.gl': string | null
  'cldr.short.gsw': string | null
  'cldr.short.gu': string | null
  'cldr.short.gv': string | null
  'cldr.short.ha': string | null
  'cldr.short.haw': string | null
  'cldr.short.he': string | null
  'cldr.short.hi': string | null
  'cldr.short.hr': string | null
  'cldr.short.hsb': string | null
  'cldr.short.hu': string | null
  'cldr.short.hy': string | null
  'cldr.short.ia': string | null
  'cldr.short.id': string | null
  'cldr.short.ig': string | null
  'cldr.short.ii': string | null
  'cldr.short.is': string | null
  'cldr.short.it': string | null
  'cldr.short.ja': string | null
  'cldr.short.jv': string | null
  'cldr.short.ka': string | null
  'cldr.short.kab': string | null
  'cldr.short.kam': string | null
  'cldr.short.kde': string | null
  'cldr.short.kea': string | null
  'cldr.short.khq': string | null
  'cldr.short.ki': string | null
  'cldr.short.kk': string | null
  'cldr.short.kln': string | null
  'cldr.short.km': string | null
  'cldr.short.kn': string | null
  'cldr.short.ko': string | null
  'cldr.short.ko_kp': string | null
  'cldr.short.kok': string | null
  'cldr.short.ks': string | null
  'cldr.short.ksb': string | null
  'cldr.short.ksf': string | null
  'cldr.short.ksh': string | null
  'cldr.short.ku': string | null
  'cldr.short.ky': string | null
  'cldr.short.lag': string | null
  'cldr.short.lb': string | null
  'cldr.short.lg': string | null
  'cldr.short.lkt': string | null
  'cldr.short.ln': string | null
  'cldr.short.lo': string | null
  'cldr.short.lrc': string | null
  'cldr.short.lt': string | null
  'cldr.short.lu': string | null
  'cldr.short.luo': string | null
  'cldr.short.luy': string | null
  'cldr.short.lv': string | null
  'cldr.short.mas': string | null
  'cldr.short.mer': string | null
  'cldr.short.mfe': string | null
  'cldr.short.mg': string | null
  'cldr.short.mgh': string | null
  'cldr.short.mi': string | null
  'cldr.short.mk': string | null
  'cldr.short.ml': string | null
  'cldr.short.mn': string | null
  'cldr.short.mr': string | null
  'cldr.short.ms': string | null
  'cldr.short.mt': string | null
  'cldr.short.mua': string | null
  'cldr.short.my': string | null
  'cldr.short.mzn': string | null
  'cldr.short.naq': string | null
  'cldr.short.nb': string | null
  'cldr.short.nd': string | null
  'cldr.short.ne': string | null
  'cldr.short.nl': string | null
  'cldr.short.nmg': string | null
  'cldr.short.nn': string | null
  'cldr.short.nyn': string | null
  'cldr.short.om': string | null
  'cldr.short.or': string | null
  'cldr.short.os': string | null
  'cldr.short.pa': string | null
  'cldr.short.pl': string | null
  'cldr.short.ps': string | null
  'cldr.short.ps_pk': string | null
  'cldr.short.pt': string | null
  'cldr.short.pt_ao': string | null
  'cldr.short.qu': string | null
  'cldr.short.rm': string | null
  'cldr.short.rn': string | null
  'cldr.short.ro': string | null
  'cldr.short.ro_md': string | null
  'cldr.short.rof': string | null
  'cldr.short.ru': string | null
  'cldr.short.ru_ua': string | null
  'cldr.short.sah': string | null
  'cldr.short.sbp': string | null
  'cldr.short.sd': string | null
  'cldr.short.se': string | null
  'cldr.short.se_fi': string | null
  'cldr.short.seh': string | null
  'cldr.short.sg': string | null
  'cldr.short.shi': string | null
  'cldr.short.shi_latn': string | null
  'cldr.short.si': string | null
  'cldr.short.sk': string | null
  'cldr.short.sl': string | null
  'cldr.short.smn': string | null
  'cldr.short.sn': string | null
  'cldr.short.so': string | null
  'cldr.short.sq': string | null
  'cldr.short.sr': string | null
  'cldr.short.sr_cyrl_ba': string | null
  'cldr.short.sr_cyrl_me': string | null
  'cldr.short.sr_cyrl_xk': string | null
  'cldr.short.sr_latn': string | null
  'cldr.short.sr_latn_ba': string | null
  'cldr.short.sr_latn_me': string | null
  'cldr.short.sr_latn_xk': string | null
  'cldr.short.sv': string | null
  'cldr.short.sw': string | null
  'cldr.short.sw_cd': string | null
  'cldr.short.sw_ke': string | null
  'cldr.short.ta': string | null
  'cldr.short.te': string | null
  'cldr.short.teo': string | null
  'cldr.short.tg': string | null
  'cldr.short.th': string | null
  'cldr.short.ti': string | null
  'cldr.short.tk': string | null
  'cldr.short.to': string | null
  'cldr.short.tr': string | null
  'cldr.short.tt': string | null
  'cldr.short.twq': string | null
  'cldr.short.tzm': string | null
  'cldr.short.ug': string | null
  'cldr.short.uk': string | null
  'cldr.short.ur': string | null
  'cldr.short.ur_in': string | null
  'cldr.short.uz': string | null
  'cldr.short.uz_cyrl': string | null
  'cldr.short.vai': string | null
  'cldr.short.vai_latn': string | null
  'cldr.short.vi': string | null
  'cldr.short.wae': string | null
  'cldr.short.wo': string | null
  'cldr.short.xog': string | null
  'cldr.short.yav': string | null
  'cldr.short.yi': string | null
  'cldr.short.yo': string | null
  'cldr.short.yo_bj': string | null
  'cldr.short.yue': string | null
  'cldr.short.yue_hans': string | null
  'cldr.short.zgh': string | null
  'cldr.short.zh': string | null
  'cldr.short.zh_hant': string | null
  'cldr.short.zh_hant_hk': string | null
  'cldr.short.zu': string | null
  'cldr.variant.af': string | null
  'cldr.variant.agq': string | null
  'cldr.variant.ak': string | null
  'cldr.variant.am': string | null
  'cldr.variant.ar': string | null
  'cldr.variant.ar_ae': string | null
  'cldr.variant.ar_ly': string | null
  'cldr.variant.ar_sa': string | null
  'cldr.variant.as': string | null
  'cldr.variant.asa': string | null
  'cldr.variant.ast': string | null
  'cldr.variant.az': string | null
  'cldr.variant.az_cyrl': string | null
  'cldr.variant.bas': string | null
  'cldr.variant.be': string | null
  'cldr.variant.bez': string | null
  'cldr.variant.bg': string | null
  'cldr.variant.bm': string | null
  'cldr.variant.bn': string | null
  'cldr.variant.bn_in': string | null
  'cldr.variant.br': string | null
  'cldr.variant.brx': string | null
  'cldr.variant.bs': string | null
  'cldr.variant.bs_cyrl': string | null
  'cldr.variant.ca': string | null
  'cldr.variant.ccp': string | null
  'cldr.variant.ce': string | null
  'cldr.variant.ceb': string | null
  'cldr.variant.cgg': string | null
  'cldr.variant.chr': string | null
  'cldr.variant.ckb': string | null
  'cldr.variant.cs': string | null
  'cldr.variant.cy': string | null
  'cldr.variant.da': string | null
  'cldr.variant.dav': string | null
  'cldr.variant.de': string | null
  'cldr.variant.de_at': string | null
  'cldr.variant.de_ch': string | null
  'cldr.variant.dje': string | null
  'cldr.variant.dsb': string | null
  'cldr.variant.dyo': string | null
  'cldr.variant.dz': string | null
  'cldr.variant.ee': string | null
  'cldr.variant.el': string | null
  'cldr.variant.en': string | null
  'cldr.variant.en_001': string | null
  'cldr.variant.en_au': string | null
  'cldr.variant.eo': string | null
  'cldr.variant.es': string | null
  'cldr.variant.es_419': string | null
  'cldr.variant.es_ar': string | null
  'cldr.variant.es_cl': string | null
  'cldr.variant.es_mx': string | null
  'cldr.variant.es_us': string | null
  'cldr.variant.et': string | null
  'cldr.variant.eu': string | null
  'cldr.variant.ewo': string | null
  'cldr.variant.fa': string | null
  'cldr.variant.fa_af': string | null
  'cldr.variant.ff': string | null
  'cldr.variant.fi': string | null
  'cldr.variant.fil': string | null
  'cldr.variant.fo': string | null
  'cldr.variant.fr': string | null
  'cldr.variant.fr_be': string | null
  'cldr.variant.fr_ca': string | null
  'cldr.variant.fur': string | null
  'cldr.variant.fy': string | null
  'cldr.variant.ga': string | null
  'cldr.variant.gd': string | null
  'cldr.variant.gl': string | null
  'cldr.variant.gsw': string | null
  'cldr.variant.gu': string | null
  'cldr.variant.ha': string | null
  'cldr.variant.he': string | null
  'cldr.variant.hi': string | null
  'cldr.variant.hr': string | null
  'cldr.variant.hsb': string | null
  'cldr.variant.hu': string | null
  'cldr.variant.hy': string | null
  'cldr.variant.ia': string | null
  'cldr.variant.id': string | null
  'cldr.variant.ig': string | null
  'cldr.variant.is': string | null
  'cldr.variant.it': string | null
  'cldr.variant.ja': string | null
  'cldr.variant.jgo': string | null
  'cldr.variant.jv': string | null
  'cldr.variant.ka': string | null
  'cldr.variant.kab': string | null
  'cldr.variant.kam': string | null
  'cldr.variant.kde': string | null
  'cldr.variant.kea': string | null
  'cldr.variant.khq': string | null
  'cldr.variant.ki': string | null
  'cldr.variant.kk': string | null
  'cldr.variant.kln': string | null
  'cldr.variant.km': string | null
  'cldr.variant.kn': string | null
  'cldr.variant.ko': string | null
  'cldr.variant.ko_kp': string | null
  'cldr.variant.kok': string | null
  'cldr.variant.ks': string | null
  'cldr.variant.ksb': string | null
  'cldr.variant.ksf': string | null
  'cldr.variant.ksh': string | null
  'cldr.variant.ku': string | null
  'cldr.variant.ky': string | null
  'cldr.variant.lag': string | null
  'cldr.variant.lb': string | null
  'cldr.variant.lg': string | null
  'cldr.variant.ln': string | null
  'cldr.variant.lo': string | null
  'cldr.variant.lt': string | null
  'cldr.variant.lu': string | null
  'cldr.variant.luo': string | null
  'cldr.variant.luy': string | null
  'cldr.variant.lv': string | null
  'cldr.variant.mas': string | null
  'cldr.variant.mer': string | null
  'cldr.variant.mfe': string | null
  'cldr.variant.mg': string | null
  'cldr.variant.mgh': string | null
  'cldr.variant.mi': string | null
  'cldr.variant.mk': string | null
  'cldr.variant.ml': string | null
  'cldr.variant.mn': string | null
  'cldr.variant.mr': string | null
  'cldr.variant.ms': string | null
  'cldr.variant.mt': string | null
  'cldr.variant.mua': string | null
  'cldr.variant.my': string | null
  'cldr.variant.mzn': string | null
  'cldr.variant.naq': string | null
  'cldr.variant.nb': string | null
  'cldr.variant.nd': string | null
  'cldr.variant.ne': string | null
  'cldr.variant.nl': string | null
  'cldr.variant.nmg': string | null
  'cldr.variant.nn': string | null
  'cldr.variant.nus': string | null
  'cldr.variant.nyn': string | null
  'cldr.variant.or': string | null
  'cldr.variant.pa': string | null
  'cldr.variant.pl': string | null
  'cldr.variant.ps': string | null
  'cldr.variant.ps_pk': string | null
  'cldr.variant.pt': string | null
  'cldr.variant.pt_ao': string | null
  'cldr.variant.qu': string | null
  'cldr.variant.rm': string | null
  'cldr.variant.rn': string | null
  'cldr.variant.ro': string | null
  'cldr.variant.ro_md': string | null
  'cldr.variant.rof': string | null
  'cldr.variant.ru': string | null
  'cldr.variant.ru_ua': string | null
  'cldr.variant.rw': string | null
  'cldr.variant.sbp': string | null
  'cldr.variant.sd': string | null
  'cldr.variant.se': string | null
  'cldr.variant.se_fi': string | null
  'cldr.variant.seh': string | null
  'cldr.variant.sg': string | null
  'cldr.variant.shi': string | null
  'cldr.variant.shi_latn': string | null
  'cldr.variant.si': string | null
  'cldr.variant.sk': string | null
  'cldr.variant.sl': string | null
  'cldr.variant.smn': string | null
  'cldr.variant.sn': string | null
  'cldr.variant.so': string | null
  'cldr.variant.sq': string | null
  'cldr.variant.sr': string | null
  'cldr.variant.sr_cyrl_ba': string | null
  'cldr.variant.sr_cyrl_me': string | null
  'cldr.variant.sr_cyrl_xk': string | null
  'cldr.variant.sr_latn': string | null
  'cldr.variant.sr_latn_ba': string | null
  'cldr.variant.sr_latn_me': string | null
  'cldr.variant.sr_latn_xk': string | null
  'cldr.variant.sv': string | null
  'cldr.variant.sw': string | null
  'cldr.variant.sw_cd': string | null
  'cldr.variant.sw_ke': string | null
  'cldr.variant.ta': string | null
  'cldr.variant.te': string | null
  'cldr.variant.teo': string | null
  'cldr.variant.tg': string | null
  'cldr.variant.th': string | null
  'cldr.variant.ti': string | null
  'cldr.variant.tk': string | null
  'cldr.variant.to': string | null
  'cldr.variant.tr': string | null
  'cldr.variant.tt': string | null
  'cldr.variant.twq': string | null
  'cldr.variant.tzm': string | null
  'cldr.variant.ug': string | null
  'cldr.variant.uk': string | null
  'cldr.variant.ur': string | null
  'cldr.variant.ur_in': string | null
  'cldr.variant.uz': string | null
  'cldr.variant.uz_cyrl': string | null
  'cldr.variant.vai': string | null
  'cldr.variant.vai_latn': string | null
  'cldr.variant.vi': string | null
  'cldr.variant.wae': string | null
  'cldr.variant.wo': string | null
  'cldr.variant.xh': string | null
  'cldr.variant.xog': string | null
  'cldr.variant.yav': string | null
  'cldr.variant.yi': string | null
  'cldr.variant.yo': string | null
  'cldr.variant.yo_bj': string | null
  'cldr.variant.yue': string | null
  'cldr.variant.yue_hans': string | null
  'cldr.variant.zgh': string | null
  'cldr.variant.zh': string | null
  'cldr.variant.zh_hant': string | null
  'cldr.variant.zh_hant_hk': string | null
  'cldr.variant.zu': string | null
}
